import "../styles/globals.css"
import { SunIcon, MoonIcon } from "@heroicons/react/24/solid"
import type { AppProps } from "next/app"
import Head from "next/head"
import { useState } from "react"
import styles from "@/styles/App.module.scss"

function MyApp({ Component, pageProps }: AppProps) {
  const [isDarkMode, setIsDarkMode] = useState<boolean>(false)

  const toggleDarkMode = () => {
    setIsDarkMode(!isDarkMode)
  }

  return (
    <div
      className={`${isDarkMode ? "dark" : "light"} ${
        !isDarkMode ? "bg-white" : "bg-black text-white"
      }`}
      style={{ minHeight: "100vh" }}
    >
      <Head>
        <title>Valonades</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header
        style={{
          display: "flex",
          justifyContent: "space-evenly",
          alignItems: "center",
        }}
        className={`h-[50px] bg-header-light dark:bg-header-dark`}
      >
        <h1 className={`font-bold text-2xl`}>ここはヘッダー</h1>

        <button
          onClick={toggleDarkMode}
          className={
            styles.DarkModeToggleButton +
            ` hover:text-white hover:bg-black` +
            ` dark:hover:bg-white dark:hover:text-black`
          }
        >
          {isDarkMode ? (
            <SunIcon className="w-[60%] h-[60%] align-none inline" />
          ) : (
            <MoonIcon className="w-[60%] h-[60%] align-none inline" />
          )}
        </button>
      </header>

      <main>
        <Component {...pageProps} />
      </main>
    </div>
  )
}

export default MyApp
