import "../styles/globals.css"
import { SunIcon, MoonIcon } from "@heroicons/react/24/solid"
import type { AppProps } from "next/app"
import Head from "next/head"
import { useState } from "react"
import styles from "@/styles/App.module.scss"




function MyApp({ Component, pageProps }: AppProps) {
  const [isDarkMode, setIsDarkMode] = useState<boolean>(false)

  const toggleDarkMode = () => {
    setIsDarkMode(!isDarkMode)
  }
  const HamburgerMenu: React.FC = () => {
    const [isOpen, setIsOpen] = useState(false);
  
    return (
      <div className="hamburger-menu">
        <button
          className="menu-btn"
          onClick={() => setIsOpen(!isOpen)}
        >
          <div className="menu-btn-line"></div>
          <div className="menu-btn-line"></div>
          <div className="menu-btn-line"></div>
        </button>
        <nav className={`menu ${isOpen ? 'active' : ''}`}>
          <ul className="menu__list">
            <p className="skill">maps</p>
            <li className="menu__item">
              <a href="#" className="menu__link">Breeze</a>
            </li>
            <li className="menu__item">
              <a href="#" className="menu__link">Bind</a>
            </li>
            <li className="menu__item">
              <a href="#" className="menu__link">Split</a>
            </li>
            <li className="menu__item">
              <a href="#" className="menu__link">Haven</a>
            </li>
            <li className="menu__item">
              <a href="#" className="menu__link">Ascent</a>
            </li>
            <li className="menu__item">
              <a href="#" className="menu__link">Icebox</a>
            </li>
            <li className="menu__item">
              <a href="#" className="menu__link">Fracture</a>
            </li>
          </ul>
        </nav>
      </div>
    );
  }
  


  return (
    <div
      className={`${isDarkMode ? "dark" : "light"} ${
        !isDarkMode ? "bg-white" : "bg-black text-white"
      }`}
      style={{ minHeight: "100vh" }}
    >
      <Head>
        <title>Valonades</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header style={{ display: "flex", justifyContent: "space-between" }}>
      <HamburgerMenu/>
    
     

        <h1 className={`font-bold text-2xl`}>ここはヘッダー</h1>

        <button
          onClick={toggleDarkMode}
          className={
            styles.DarkModeToggleButton +
            ` hover:text-white hover:bg-black` +
            ` dark:hover:bg-white dark:hover:text-black`
          }
        >
          {isDarkMode ? (
            <SunIcon className="w-[60%] h-[60%] align-none inline" />
          ) : (
            <MoonIcon className="w-[60%] h-[60%] align-none inline" />
          )}
        </button>
      </header>

      <main>
        <Component {...pageProps} />
      </main>
    </div>
  )
}

export default MyApp
